import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — Skymatch",
};

// NOTE (M10): TEMPLATE scaffold — counsel must review/finalize before public launch.
export default function TermsPage() {
  return (
    <main className="min-h-screen px-6 py-16 flex justify-center">
      <article className="w-full max-w-2xl text-sm leading-relaxed" style={{ color: "var(--text-secondary)" }}>
        <Link
          href="/"
          className="mono text-[10px] uppercase tracking-widest hover:opacity-70"
          style={{ color: "var(--text-secondary)" }}
        >
          ← back
        </Link>

        <div
          className="mt-6 mono text-[10px] uppercase tracking-widest border px-3 py-2"
          style={{ borderColor: "var(--border)", color: "var(--text-secondary)" }}
        >
          Template — pending legal review. Not yet binding.
        </div>

        <h1 className="mt-6 text-2xl font-semibold" style={{ color: "var(--text-primary)" }}>
          Terms of Service
        </h1>
        <p className="mt-1 mono text-[10px]" style={{ color: "var(--text-secondary)" }}>
          Last updated: TBD
        </p>

        <Section title="The service">
          <p>
            Skymatch helps you discover internship listings and analyze your fit against job
            postings. Results are generated by automated systems and AI models and are provided
            for informational purposes only — they are not guarantees of employment, accuracy,
            or availability of any listing.
          </p>
        </Section>

        <Section title="Acceptable use">
          <p>
            Use the service only for your own job search and in compliance with applicable law.
            Don&apos;t abuse, overload, scrape, or attempt to circumvent rate limits or access
            controls. Submit only content you have the right to submit.
          </p>
        </Section>

        <Section title="Accounts">
          <p>
            Some features require signing in. You&apos;re responsible for activity under your
            account. You may delete your account at any time from the{" "}
            <Link href="/account" className="underline" style={{ color: "var(--accent)" }}>
              Account
            </Link>{" "}
            page.
          </p>
        </Section>

        <Section title="No warranty; limitation of liability">
          <p>
            The service is provided “as is,” without warranties of any kind. To the maximum
            extent permitted by law, we are not liable for any indirect or consequential
            damages arising from your use of the service. (Final terms subject to legal review.)
          </p>
        </Section>

        <Section title="Changes">
          <p>
            We may update these terms; continued use after an update constitutes acceptance.
          </p>
        </Section>

        <Section title="Contact">
          <p>support@TBD — to be finalized before launch.</p>
        </Section>

        <p className="mt-10 mono text-[10px]" style={{ color: "var(--text-secondary)" }}>
          See also our{" "}
          <Link href="/privacy" className="underline" style={{ color: "var(--accent)" }}>
            Privacy Policy
          </Link>
          .
        </p>
      </article>
    </main>
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section className="mt-8">
      <h2 className="text-sm font-semibold uppercase tracking-wide" style={{ color: "var(--text-primary)" }}>
        {title}
      </h2>
      <div className="mt-2 space-y-2">{children}</div>
    </section>
  );
}
