"""initial schema - port of the former sqlite cache.init_db() DDL to Postgres

Creates the 16 tables + 7 indexes the backend's data layer (cache.py) uses, and seeds
metro_rotation from config.niches.SEED_METROS. This is a 1:1 translation of the DDL that
used to live in cache.init_db() (executescript), with sqlite types mapped to Postgres:
  BLOB -> BYTEA, REAL -> DOUBLE PRECISION, epoch INTEGER timestamps -> BIGINT,
  INTEGER PRIMARY KEY AUTOINCREMENT -> BIGINT GENERATED BY DEFAULT AS IDENTITY.
Booleans stay INTEGER 0/1 (is_category_page, alive) to keep cache.py callers unchanged.

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-05
"""
import time

import sqlalchemy as sa
from alembic import op

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


# One statement per entry — executed individually (psycopg3 rejects multiple commands in a
# single prepared statement). Inline `--` comments are stripped by the Postgres parser.
_TABLES = [
    """
    CREATE TABLE IF NOT EXISTS profile_cache (
        linkedin_url TEXT PRIMARY KEY,
        data         TEXT NOT NULL,
        created_at   BIGINT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS people_search_cache (
        filter_hash  TEXT PRIMARY KEY,
        data         TEXT NOT NULL,
        created_at   BIGINT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS jobs_search_cache (
        filter_hash  TEXT PRIMARY KEY,
        data         TEXT NOT NULL,
        created_at   BIGINT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS run_cache (
        url          TEXT PRIMARY KEY,
        data         TEXT NOT NULL,
        created_at   BIGINT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS url_validation_cache (
        url        TEXT PRIMARY KEY,
        data       TEXT NOT NULL,
        created_at BIGINT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS enrichment_cache (
        url        TEXT PRIMARY KEY,
        data       TEXT NOT NULL,
        created_at BIGINT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS analysis_cache (
        cache_key  TEXT PRIMARY KEY,
        data       TEXT NOT NULL,
        created_at BIGINT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS requirements_cache (
        job_hash   TEXT PRIMARY KEY,
        data       TEXT NOT NULL,
        created_at BIGINT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS job_fetch_cache (
        url_hash   TEXT PRIMARY KEY,
        data       TEXT NOT NULL,
        created_at BIGINT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS user_analysis_cache (
        cache_key  TEXT PRIMARY KEY,
        mode       TEXT NOT NULL,
        data       TEXT NOT NULL,
        created_at BIGINT NOT NULL
    )
    """,
    """
    CREATE TABLE IF NOT EXISTS url_liveness_cache (
        url        TEXT PRIMARY KEY,
        alive      INTEGER NOT NULL,
        checked_at BIGINT NOT NULL
    )
    """,
    # Per-(profile, role) "why you fit" reasoning from /internships/annotate (30-day TTL).
    """
    CREATE TABLE IF NOT EXISTS annotate_cache (
        cache_key  TEXT PRIMARY KEY,
        data       TEXT NOT NULL,
        created_at BIGINT NOT NULL
    )
    """,
    # Append-only ledger of Claude spend + cache savings (written by lib/cost.py).
    # kind='call' rows carry real tokens/usd; kind='hit' rows carry est_saved_usd (usd=0).
    """
    CREATE TABLE IF NOT EXISTS cost_events (
        id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        created_at         BIGINT NOT NULL,
        kind               TEXT NOT NULL,        -- 'call' | 'hit'
        session            TEXT,
        label              TEXT,
        model              TEXT,
        input_tokens       INTEGER NOT NULL DEFAULT 0,
        output_tokens      INTEGER NOT NULL DEFAULT 0,
        cache_read_tokens  INTEGER NOT NULL DEFAULT 0,
        cache_write_tokens INTEGER NOT NULL DEFAULT 0,
        usd                DOUBLE PRECISION NOT NULL DEFAULT 0,
        est_saved_usd      DOUBLE PRECISION NOT NULL DEFAULT 0
    )
    """,
    # Tiny persistent key/value flags (e.g. the manual kill switch, key='kill_switch').
    """
    CREATE TABLE IF NOT EXISTS app_flags (
        key        TEXT PRIMARY KEY,
        value      TEXT NOT NULL,
        updated_at BIGINT NOT NULL
    )
    """,
    # Pre-ingested job listings (worker/ingest.py) — a QUERYABLE COLLECTION the serving
    # layer filters by niche/bucket/freshness. Precompute columns (parsed_json/embedding/
    # ...) are created here from the start; parsed_at IS NULL is the "needs work" sentinel.
    """
    CREATE TABLE IF NOT EXISTS listing_store (
        url                TEXT NOT NULL,
        bucket             TEXT NOT NULL,      -- startup|big_tech|local|reach
        niche_key          TEXT NOT NULL,      -- Niche.key, or '_reach' pool
        company            TEXT,
        search_title       TEXT,
        snippet            TEXT,
        verified_location  TEXT,
        is_category_page   INTEGER NOT NULL DEFAULT 0,
        status             TEXT NOT NULL DEFAULT 'valid',  -- valid|dead
        validation_reason  TEXT,
        raw_json           TEXT,
        first_seen         BIGINT NOT NULL,
        last_seen          BIGINT NOT NULL,
        last_validated     BIGINT NOT NULL,
        parsed_json        TEXT,     -- {title,company,company_description,location,skills[],
                                     --  seniority,role_category,is_internship,sponsorship}
        embedding          BYTEA,    -- normalized float32 vector (np.tobytes)
        embedding_model    TEXT,     -- model id the vector was produced with
        embedding_dim      INTEGER,  -- authoritative vector length
        content_hash       TEXT,     -- hash of the embed text the parse was keyed on
        parsed_at          BIGINT,   -- when parse+embed last ran (NULL = unparsed)
        -- Composite key: the SAME url legitimately belongs to multiple contexts
        -- (Stripe's listing is big_tech for every CS niche AND in the _reach pool).
        PRIMARY KEY (niche_key, bucket, url)
    )
    """,
    # Which metros the worker refreshes `local` for / serve local from the index. Seeded
    # with SEED_METROS; serving promotes uncovered metros here on first request.
    """
    CREATE TABLE IF NOT EXISTS metro_rotation (
        metro     TEXT PRIMARY KEY,
        added_at  BIGINT NOT NULL,
        source    TEXT NOT NULL        -- 'seed' | 'serving'
    )
    """,
]

_INDEXES = [
    "CREATE INDEX IF NOT EXISTS idx_user_analysis_mode ON user_analysis_cache(mode)",
    "CREATE INDEX IF NOT EXISTS idx_cost_events_created ON cost_events(created_at)",
    "CREATE INDEX IF NOT EXISTS idx_listing_niche_bucket ON listing_store(niche_key, bucket)",
    "CREATE INDEX IF NOT EXISTS idx_listing_bucket ON listing_store(bucket)",
    "CREATE INDEX IF NOT EXISTS idx_listing_freshness ON listing_store(last_validated)",
    "CREATE INDEX IF NOT EXISTS idx_listing_status ON listing_store(status)",
    "CREATE INDEX IF NOT EXISTS idx_listing_unparsed ON listing_store(status, parsed_at)",
]

# Drop order for downgrade (no FKs, so order is cosmetic).
_DROP_TABLES = [
    "metro_rotation", "listing_store", "app_flags", "cost_events", "annotate_cache",
    "url_liveness_cache", "user_analysis_cache", "job_fetch_cache", "requirements_cache",
    "analysis_cache", "enrichment_cache", "url_validation_cache", "run_cache",
    "jobs_search_cache", "people_search_cache", "profile_cache",
]


def upgrade() -> None:
    for ddl in _TABLES:
        op.execute(ddl)
    for ddl in _INDEXES:
        op.execute(ddl)

    # Seed the metro rotation (idempotent). Import here (not at module top) so merely
    # listing revisions never imports app config. prepend_sys_path=. puts backend/ on path.
    from config.niches import SEED_METROS

    now = int(time.time())
    op.get_bind().execute(
        sa.text(
            "INSERT INTO metro_rotation (metro, added_at, source) "
            "VALUES (:m, :t, 'seed') ON CONFLICT (metro) DO NOTHING"
        ),
        [{"m": m, "t": now} for m in SEED_METROS],
    )


def downgrade() -> None:
    for table in _DROP_TABLES:
        op.execute(f"DROP TABLE IF EXISTS {table}")
